### ISSUE TITLE
Setting up 'vendor' folder in the project tree

### ISSUE THREAD

**Issue by catobus** [abiee/mastering-backbone#3]
Hi Abiee, 

How do you setup the dependencies in the '_vendor_' folder of the project tree? For example '_/ch07/app/js/vendor/_' contains '_jquery-2.1.4.min.js_'.  '_npm_' brings dependencies into '_node_modules_' folder. Do you then manually copy these from '_node_modules_' to '_vendor_' folder in the project tree?

Thanks!

**Comment by abiee** [comment]
Hi @catobus I feel sorry for the late response. For chapter 7 I see that I have some wrong code, sorry for that I will make an update of all chapters to be sure that are working right with node 5. I will ping you once I update the chaper 07.

Here browserify makes the magic. Dependencies installed via `npm` will be available with the `require()` function provided by browserify.

```
var jquery = require('jquery');
```

The line above above will tell to browserify to load jquery, it will be loaded from the `node_modules`. So, in this way the `vendor` path is not needed anymore.

**Comment by catobus** [comment]
While discovering more about _browserify_ I already figured it out, however thank you very much for confirming it and for your reply!
