### ISSUE TITLE
Backbone and ES6 classes

### ISSUE THREAD

**Issue by DavidUnzue** [abiee/mastering-backbone#4]
Hi @abiee ,

since you are using ES6 throughout your code, and specially declaring classes the ES6 way, I wanted to ask if you are aware of this:
http://benmccormick.org/2015/07/06/backbone-and-es6-classes-revisited/

To what extent does it affect your code, if it does at all?

**Comment by abiee** [comment]
@DavidUnzue Yes I'm aware of this; indeed, I'm using the same strategies and suggestions that the author of the article mentions. Have you any issue running the code?

**Comment by DavidUnzue** [comment]
You are right, I went through the code again and realised now, that you are already doing it like that. No issues so far. I will close this :-)
